/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NeedsRegisterRouteImport } from './routes/needs-register'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTraspasoRouteImport } from './routes/admin/traspaso'
import { Route as AdminNeedsRouteImport } from './routes/admin/needs'
import { Route as AdminHubsRouteImport } from './routes/admin/hubs'
import { Route as AdminFleetRouteImport } from './routes/admin/fleet'
import { Route as AdminCoordinatorRouteImport } from './routes/admin/coordinator'
import { Route as AdminConvoysRouteImport } from './routes/admin/convoys'
import { Route as AdminCatalogRouteImport } from './routes/admin/catalog'
import { Route as AdminCargarRouteImport } from './routes/admin/cargar'
import { Route as AdminHubsHubIdRouteImport } from './routes/admin/hubs_.$hubId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedsRegisterRoute = NeedsRegisterRouteImport.update({
  id: '/needs-register',
  path: '/needs-register',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTraspasoRoute = AdminTraspasoRouteImport.update({
  id: '/traspaso',
  path: '/traspaso',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNeedsRoute = AdminNeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHubsRoute = AdminHubsRouteImport.update({
  id: '/hubs',
  path: '/hubs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoordinatorRoute = AdminCoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConvoysRoute = AdminConvoysRouteImport.update({
  id: '/convoys',
  path: '/convoys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCargarRoute = AdminCargarRouteImport.update({
  id: '/cargar',
  path: '/cargar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHubsHubIdRoute = AdminHubsHubIdRouteImport.update({
  id: '/hubs_/$hubId',
  path: '/hubs/$hubId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/needs-register': typeof NeedsRegisterRoute
  '/register': typeof RegisterRoute
  '/admin/cargar': typeof AdminCargarRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/convoys': typeof AdminConvoysRoute
  '/admin/coordinator': typeof AdminCoordinatorRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/needs': typeof AdminNeedsRoute
  '/admin/traspaso': typeof AdminTraspasoRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/hubs/$hubId': typeof AdminHubsHubIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/needs-register': typeof NeedsRegisterRoute
  '/register': typeof RegisterRoute
  '/admin/cargar': typeof AdminCargarRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/convoys': typeof AdminConvoysRoute
  '/admin/coordinator': typeof AdminCoordinatorRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/needs': typeof AdminNeedsRoute
  '/admin/traspaso': typeof AdminTraspasoRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/hubs/$hubId': typeof AdminHubsHubIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/needs-register': typeof NeedsRegisterRoute
  '/register': typeof RegisterRoute
  '/admin/cargar': typeof AdminCargarRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/convoys': typeof AdminConvoysRoute
  '/admin/coordinator': typeof AdminCoordinatorRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/hubs': typeof AdminHubsRoute
  '/admin/needs': typeof AdminNeedsRoute
  '/admin/traspaso': typeof AdminTraspasoRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/hubs_/$hubId': typeof AdminHubsHubIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/map'
    | '/needs-register'
    | '/register'
    | '/admin/cargar'
    | '/admin/catalog'
    | '/admin/convoys'
    | '/admin/coordinator'
    | '/admin/fleet'
    | '/admin/hubs'
    | '/admin/needs'
    | '/admin/traspaso'
    | '/admin/users'
    | '/admin/'
    | '/admin/hubs/$hubId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/map'
    | '/needs-register'
    | '/register'
    | '/admin/cargar'
    | '/admin/catalog'
    | '/admin/convoys'
    | '/admin/coordinator'
    | '/admin/fleet'
    | '/admin/hubs'
    | '/admin/needs'
    | '/admin/traspaso'
    | '/admin/users'
    | '/admin'
    | '/admin/hubs/$hubId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/map'
    | '/needs-register'
    | '/register'
    | '/admin/cargar'
    | '/admin/catalog'
    | '/admin/convoys'
    | '/admin/coordinator'
    | '/admin/fleet'
    | '/admin/hubs'
    | '/admin/needs'
    | '/admin/traspaso'
    | '/admin/users'
    | '/admin/'
    | '/admin/hubs_/$hubId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  NeedsRegisterRoute: typeof NeedsRegisterRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needs-register': {
      id: '/needs-register'
      path: '/needs-register'
      fullPath: '/needs-register'
      preLoaderRoute: typeof NeedsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/traspaso': {
      id: '/admin/traspaso'
      path: '/traspaso'
      fullPath: '/admin/traspaso'
      preLoaderRoute: typeof AdminTraspasoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/needs': {
      id: '/admin/needs'
      path: '/needs'
      fullPath: '/admin/needs'
      preLoaderRoute: typeof AdminNeedsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hubs': {
      id: '/admin/hubs'
      path: '/hubs'
      fullPath: '/admin/hubs'
      preLoaderRoute: typeof AdminHubsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coordinator': {
      id: '/admin/coordinator'
      path: '/coordinator'
      fullPath: '/admin/coordinator'
      preLoaderRoute: typeof AdminCoordinatorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/convoys': {
      id: '/admin/convoys'
      path: '/convoys'
      fullPath: '/admin/convoys'
      preLoaderRoute: typeof AdminConvoysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cargar': {
      id: '/admin/cargar'
      path: '/cargar'
      fullPath: '/admin/cargar'
      preLoaderRoute: typeof AdminCargarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hubs_/$hubId': {
      id: '/admin/hubs_/$hubId'
      path: '/hubs/$hubId'
      fullPath: '/admin/hubs/$hubId'
      preLoaderRoute: typeof AdminHubsHubIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCargarRoute: typeof AdminCargarRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminConvoysRoute: typeof AdminConvoysRoute
  AdminCoordinatorRoute: typeof AdminCoordinatorRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminHubsRoute: typeof AdminHubsRoute
  AdminNeedsRoute: typeof AdminNeedsRoute
  AdminTraspasoRoute: typeof AdminTraspasoRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminHubsHubIdRoute: typeof AdminHubsHubIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCargarRoute: AdminCargarRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminConvoysRoute: AdminConvoysRoute,
  AdminCoordinatorRoute: AdminCoordinatorRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminHubsRoute: AdminHubsRoute,
  AdminNeedsRoute: AdminNeedsRoute,
  AdminTraspasoRoute: AdminTraspasoRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminHubsHubIdRoute: AdminHubsHubIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  NeedsRegisterRoute: NeedsRegisterRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
